version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5050:5050"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT_FORMAT: json
    volumes:
      - ./app:/app

